### ISSUE TITLE
Issues facing in adding library - use of undeclared identifier "iodevice" 

### ISSUE THREAD

**Issue by firmware-zeleno** [ceciletti/escpos-qt#1]
Thank you very much for creating this library for thermal printer integration with QT. 
I am trying to integrate this library with my application, using this thermal printer - https://eurocoincomponents.com/product/ms-fpt201k-panel-printer/ It works on ESC/POS command. 

Queries : 
1. Where do I need to define the VID and PID for initializing the device? 
2. When adding ioDevice->write(b.data()); to send data to printer, QT creator throws me an error - use of undeclared identifier "iodevice" . 

Please help me to solve the issue. 
I am running QT creator on windows.

**Comment by dantti** [comment]
1. Not sure what do you mean by VID or PID
2. Well you must first connect to your printer, this library only prepares the commands to send to your printer, if you are going to send via serial use a QSerialPort, QTcpSocket, QBluetoothSocket, any QIODevice subclass can be used, or just get the data (using a QBuffer) and send to whatever you are using to communicate.
